SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone::
    .ifdef ENGLISH
    .string "Have you gone to the SAFARI ZONE\n"
    .string "in FUCHSIA CITY?\p"
    .string "There are many kinds of rare\n"
    .string "POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¿Has ido a la ZONA del SAFARI\n"
    .string "en CIUDAD FUCSIA?\p"
    .string "¡Había muchos tipos raros\n"
    .string "de POKéMON!$"
    .endif

SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome::
    .ifdef ENGLISH
    .string "Me and my daddy think the SAFARI\n"
    .string "ZONE is awesome!\l"
    .string "I wish we could go there again.$"
    .endif
    .ifdef SPANISH
    .string "¡Mi padre y yo pensamos que\n"
    .string "la ZONA del SAFARI es genial!$"
    .endif

