SSAnne_1F_Room4_Text_WaiterCherryPiePlease::
    .ifdef ENGLISH
    .string "Waiter, I would like a cherry pie,\n"
    .string "please!$"
    .endif
    .ifdef SPANISH
    .string "¡Camarero, me gustaría tomar\n"
    .string "un trozo de tarta de cereza!$"
    .endif

SSAnne_1F_Room4_Text_WaitressCherryPiePlease::
    .ifdef ENGLISH
    .string "Waitress, I would like a cherry\n"
    .string "pie, please!$"
    .endif
    .ifdef SPANISH
    .string "¡Camarero, me gustaría tomar\n"
    .string "un trozo de tarta de cereza!$"
    .endif

