MtMoon_1F_Text_MarcosIntro::
    .ifdef ENGLISH
    .string "WHOA!\n"
    .string "You shocked me!\l"
    .string "…Oh, you're just a kid!$"
    .endif
    .ifdef SPANISH
    .string "¡GUAU!\n¡Me has impresionado!\l"
    .string "¡Pero si eres muy joven!$"
    .endif

MtMoon_1F_Text_MarcosDefeat::
    .ifdef ENGLISH
    .string "Wow!\n"
    .string "Shocked again!$"
    .endif
    .ifdef SPANISH
    .string "¡Uau!\n"
    .string "¡Has vuelto a impresionarme!$"
    .endif

MtMoon_1F_Text_MarcosPostBattle::
    .ifdef ENGLISH
    .string "Kids like you shouldn't be\n"
    .string "wandering around here in the dark.$"
    .endif
    .ifdef SPANISH
    .string "¡No tienes edad para estar aquí!$"
    .endif

MtMoon_1F_Text_JoshIntro::
    .ifdef ENGLISH
    .string "Did you come to explore the cave,\n"
    .string "too?$"
    .endif
    .ifdef SPANISH
    .string "¿Estás aquí para explorar?$"
    .endif

MtMoon_1F_Text_JoshDefeat::
    .ifdef ENGLISH
    .string "Losing stinks!\n"
    .string "It's so uncool.$"
    .endif
    .ifdef SPANISH
    .string "¡Perder es lo peor!$"
    .endif

MtMoon_1F_Text_JoshPostBattle::
    .ifdef ENGLISH
    .string "I came all the way down here to\n"
    .string "show off to girls.$"
    .endif
    .ifdef SPANISH
    .string "¡Vine aquí para impresionar\n"
    .string "a las chicas!$"
    .endif

MtMoon_1F_Text_MiriamIntro::
    .ifdef ENGLISH
    .string "Wow! It's way bigger in here than\n"
    .string "I thought!$"
    .endif
    .ifdef SPANISH
    .string "¡Uau! ¡Esto es mucho más grande\n"
    .string "de lo que creía!$"
    .endif

MtMoon_1F_Text_MiriamDefeat::
    .ifdef ENGLISH
    .string "Oh!\n"
    .string "I lost it!$"
    .endif
    .ifdef SPANISH
    .string "¡Oh!\n¡He perdido!$"
    .endif

MtMoon_1F_Text_MiriamPostBattle::
    .ifdef ENGLISH
    .string "How do you get out of here?\n"
    .string "It's so big, I may get lost.$"
    .endif
    .ifdef SPANISH
    .string "¿Cómo se sale de aquí?$"
    .endif

MtMoon_1F_Text_JovanIntro::
    .ifdef ENGLISH
    .string "What!\n"
    .string "Don't sneak up on me!$"
    .endif
    .ifdef SPANISH
    .string "¡Eh!\n"
    .string "¡No te pases conmigo!$"
    .endif

MtMoon_1F_Text_JovanDefeat::
    .ifdef ENGLISH
    .string "My POKéMON won't do!$"
    .endif
    .ifdef SPANISH
    .string "¡Mis POKéMON no lo han conseguido!$"
    .endif

MtMoon_1F_Text_JovanPostBattle::
    .ifdef ENGLISH
    .string "I have to find stronger POKéMON.\n"
    .string "Where might they be?$"
    .endif
    .ifdef SPANISH
    .string "¡Debo encontrar POKéMON\n"
    .string "más fuertes!$"
    .endif

MtMoon_1F_Text_IrisIntro::
    .ifdef ENGLISH
    .string "What?\n"
    .string "I'm waiting for my friends to find\l"
    .string "me here.$"
    .endif
    .ifdef SPANISH
    .string "¿Qué?\n"
    .string "Estoy esperando aquí a mis amigos.$"
    .endif

MtMoon_1F_Text_IrisDefeat::
    .ifdef ENGLISH
    .string "I lost?$"
    .endif
    .ifdef SPANISH
    .string "¿He perdido?$"
    .endif

MtMoon_1F_Text_IrisPostBattle::
    .ifdef ENGLISH
    .string "I came because I heard there are\n"
    .string "some very rare fossils here.$"
    .endif
    .ifdef SPANISH
    .string "Dicen que aquí hay unos fósiles\n"
    .string "muy raros.$"
    .endif

MtMoon_1F_Text_KentIntro::
    .ifdef ENGLISH
    .string "Suspicious men are in the cave.\n"
    .string "What about you?$"
    .endif
    .ifdef SPANISH
    .string "En la cueva hay unos hombres\n"
    .string "muy sospechosos. ¿Y tú, qué?$"
    .endif

MtMoon_1F_Text_KentDefeat::
    .ifdef ENGLISH
    .string "You got me!$"
    .endif
    .ifdef SPANISH
    .string "¡Me has ganado!$"
    .endif

MtMoon_1F_Text_KentPostBattle::
    .ifdef ENGLISH
    .string "I saw them!\n"
    .string "I'm sure they're from TEAM ROCKET!$"
    .endif
    .ifdef SPANISH
    .string "¡Los he visto!\n"
    .string "¡Son del TEAM ROCKET! ¡Seguro!$"
    .endif

MtMoon_1F_Text_RobbyIntro::
    .ifdef ENGLISH
    .string "You need to go through this cave\n"
    .string "to get to CERULEAN CITY.$"
    .endif
    .ifdef SPANISH
    .string "¡Cruza esta cueva y llegarás\n"
    .string "a CIUDAD CELESTE!$"
    .endif

MtMoon_1F_Text_RobbyDefeat::
    .ifdef ENGLISH
    .string "I lost.$"
    .endif
    .ifdef SPANISH
    .string "He perdido.$"
    .endif

MtMoon_1F_Text_RobbyPostBattle::
    .ifdef ENGLISH
    .string "ZUBAT is tough!\n"
    .string "But if you can catch one, you'll\l"
    .string "be able to count on it.$"
    .endif
    .ifdef SPANISH
    .string "¡ZUBAT es muy fuerte!\n"
    .string "¡Atrapar uno sería muy útil!$"
    .endif

MtMoon_1F_Text_ZubatIsABloodsucker::
    .ifdef ENGLISH
    .string "Beware!\n"
    .string "ZUBAT is a bloodsucker!$"
    .endif
    .ifdef SPANISH
    .string "¡Cuidado!\n"
    .string "¡Los ZUBAT son unos chupasangre!$"
    .endif

MtMoon_1F_Text_BrockHelpsExcavateFossils::
    .ifdef ENGLISH
    .string "Hi, I'm excavating for fossils here\n"
    .string "under MT. MOON.\p"
    .string "Sometimes, BROCK of PEWTER GYM\n"
    .string "lends me a hand.$"
    .endif
    .ifdef SPANISH
    .string "Estoy buscando fósiles en las\n"
    .string "entrañas del MT. MOON.\p"
    .string "A veces me ayuda BROCK,\n"
    .string "del GIMNASIO de PLATEADA.$"
    .endif
