SSAnne_B1F_Room5_Text_MachokeHasStrengthToMoveRocks::
    .ifdef ENGLISH
    .string "My buddy MACHOKE is super strong!\p"
    .string "He has enough STRENGTH to move\n"
    .string "big rocks!$"
    .endif
    .ifdef SPANISH
    .string "¡Mi amigo, MACHOKE,\n"
    .string "es superfuerte!\p"
    .string "¡Tiene tanta FUERZA que puede\n"
    .string "mover hasta grandes rocas!$"
    .endif

SSAnne_B1F_Room5_Text_Machoke::
    .ifdef ENGLISH
    .string "MACHOKE: Gwoh! Goggoh!$"
    .endif
    .ifdef SPANISH
    .string "MACHOKE: ¡Cho! ¡Chokecho!$"
    .endif

