SSAnne_1F_Room5_Text_ArthurIntro::
    .ifdef ENGLISH
    .string "You insolent pup!\n"
    .string "How dare you barge in!$"
    .endif
    .ifdef SPANISH
    .string "¡Oye, tú, impertinente!\n"
    .string "¿Cómo te atreves a entrar aquí?$"
    .endif

SSAnne_1F_Room5_Text_ArthurDefeat::
    .ifdef ENGLISH
    .string "Humph! You rude child!\n"
    .string "You have no sense of courtesy!$"
    .endif
    .ifdef SPANISH
    .string "¡Oye!\n"
    .string "¡¡No tienes educación!!$"
    .endif

SSAnne_1F_Room5_Text_ArthurPostBattle::
    .ifdef ENGLISH
    .string "I wish to be left alone!\n"
    .string "Get out!$"
    .endif
    .ifdef SPANISH
    .string "¡Me gustaría que me dejaras solo!\n"
    .string "¡¡Fuera de aquí!!$"
    .endif

