SSAnne_3F_Corridor_Text_CaptainTeachesCutToMons::
    .ifdef ENGLISH
    .string "Our CAPTAIN is a sword master.\n"
    .string "He's awesome at using CUT.\p"
    .string "They say he even teaches CUT\n"
    .string "to POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "¡Nuestro CAPITÁN es un maestro\n"
    .string "de la esgrima!\p"
    .string "¡Dicen que enseña a los POKéMON\n"
    .string "la técnica del CORTE!$"
    .endif

