SSAnne_Kitchen_Text_BusyOutOfTheWay::
    .ifdef ENGLISH
    .string "You, mon petit!\n"
    .string "We're busy here!\l"
    .string "Out of the way!$"
    .endif
    .ifdef SPANISH
    .string "¡Hola, peque!\n"
    .string "¡Ahora estamos ocupados!\l"
    .string "¡Fuera de aquí!$"
    .endif

SSAnne_Kitchen_Text_SawOddBerryInTrash::
    .ifdef ENGLISH
    .string "I saw an odd BERRY in the trash.\n"
    .string "I wonder what that was?$"
    .endif
    .ifdef SPANISH
    .string "He visto una BAYA muy rara en la\n"
    .string "basura. No sé de qué tipo será...$"
    .endif

SSAnne_Kitchen_Text_SoBusyImDizzy::
    .ifdef ENGLISH
    .string "I'm so busy I'm getting dizzy!\n"
    .string "You have to give me room here!$"
    .endif
    .ifdef SPANISH
    .string "¡Estoy tan ocupado que me estoy\n"
    .string "mareando!$"
    .endif

SSAnne_Kitchen_Text_PeelSpudsEveryDay::
    .ifdef ENGLISH
    .string "Hum-de-hum-de-ho…\p"
    .string "I peel spuds every day!\n"
    .string "Hum-hum…$"
    .endif
    .ifdef SPANISH
    .string "¿Por qué? ¿Por qué yo?\p"
    .string "¡Me paso todo el día pelando\n"
    .string "patatas!$"
    .endif

SSAnne_Kitchen_Text_HearAboutSnorlaxItsAGlutton::
    .ifdef ENGLISH
    .string "Did you hear about SNORLAX?\n"
    .string "It's a glutton.\p"
    .string "No other POKéMON eats and sleeps\n"
    .string "the way SNORLAX can and does!$"
    .endif
    .ifdef SPANISH
    .string "¿Has oído hablar de SNORLAX?\p"
    .string "¡Se pasa todo el día comiendo\n"
    .string "y durmiendo!$"
    .endif

SSAnne_Kitchen_Text_OnlyGetToPeelOnions::
    .ifdef ENGLISH
    .string "Snivel… Sniff…\p"
    .string "I only get to peel onions…\n"
    .string "Snivel…$"
    .endif
    .ifdef SPANISH
    .string "Sniff...sniff...\p"
    .string "Yo sólo pelo cebollas...\n"
    .string "Sniff...$"
    .endif

SSAnne_Kitchen_Text_IAmLeChefMainCourseIs::
    .ifdef ENGLISH
    .string "Er-hem!\n"
    .string "Indeed I am le CHEF!\p"
    .string "Le main course is$"
    .endif
    .ifdef SPANISH
    .string "¡Ejem!\n"
    .string "¡Por algo soy el CHEF!\p"
    .string "El menú es:$"
    .endif

SSAnne_Kitchen_Text_SalmonDuSalad::
    .ifdef ENGLISH
    .string "Salmon du Salad!\p"
    .string "Les guests may gripe it's fish\n"
    .string "again, however!$"
    .endif
    .ifdef SPANISH
    .string "¡Ensalada de salmón!\p"
    .string "¡Pero puede que los clientes se\n"
    .string "quejen de tanto repetir pescado!$"
    .endif

SSAnne_Kitchen_Text_EelsAuBarbecue::
    .ifdef ENGLISH
    .string "Eels au Barbecue!\p"
    .string "Les guests will mutiny, I fear.$"
    .endif
    .ifdef SPANISH
    .string "¡Anguilas a la barbacoa!\p"
    .string "¡Me temo que los clientes se van\n"
    .string "a amotinar!$"
    .endif

SSAnne_Kitchen_Text_PrimeBeefsteak::
    .ifdef ENGLISH
    .string "Prime Beefsteak!\p"
    .string "But, have I enough fillets du\n"
    .string "beef?$"
    .endif
    .ifdef SPANISH
    .string "¡Filetes de ternera!\p"
    .string "Pero ¡¿tengo bastantes filetes\n"
    .string "para todos?!$"
    .endif

