SSAnne_1F_Room6_Text_TakeAShortRest::
    .ifdef ENGLISH
    .string "You look tired. Would you like to\n"
    .string "take a short rest?$"
    .endif
    .ifdef SPANISH
    .string "¡Tienes una cara de agotamiento!\n"
    .string "¿Quieres descansar un ratito?$"
    .endif

SSAnne_1F_Room6_Text_GladEveryoneIsRefreshed::
    .ifdef ENGLISH
    .string "I'm glad to see that everyone is\n"
    .string "looking refreshed and chipper.$"
    .endif
    .ifdef SPANISH
    .string "¡Eso ya es otra cosa! ¡Me encanta\n"
    .string "ver a todo el mundo descansado!$"
    .endif

SSAnne_1F_Room6_Text_SorryYouLookLikeMyBrother::
    .ifdef ENGLISH
    .string "Oh, I'm sorry for fussing over you.\n"
    .string "You look like my little brother…$"
    .endif
    .ifdef SPANISH
    .string "Bueno, yo lo decía por tu bien.\n"
    .string "Es que me recuerdas a mi hermano\l"
    .string "pequeño...$"
    .endif

SSAnne_1F_Room6_Text_SorryYouLookLikeMySister::
    .ifdef ENGLISH
    .string "Oh, I'm sorry for fussing over you.\n"
    .string "You look like my little sister…$"
    .endif
    .ifdef SPANISH
    .string "Bueno, yo lo decía por tu bien.\n"
    .string "Es que me recuerdas a mi hermana\l"
    .string "pequeña...$"
    .endif

