SSAnne_CaptainsOffice_Text_CaptainIFeelSeasick::
    .ifdef ENGLISH
    .string "CAPTAIN: Ooargh…\n"
    .string "I feel hideous…\l"
    .string "Urrp! Seasick…$"
    .endif
    .ifdef SPANISH
    .string "CAPITÁN: ¡Puajj!\n"
    .string "Me siento fatal.\l"
    .string "Me he mareado...$"
    .endif

SSAnne_CaptainsOffice_Text_RubbedCaptainsBack::
    .ifdef ENGLISH
    .string "{PLAYER} rubbed the CAPTAIN's\n"
    .string "back!\p"
    .string "Rub-rub…\n"
    .string "Rub-rub…$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} le dio un masaje\n"
    .string "al CAPITÁN!\p"
    .string "(Scratch)...\n"
    .string "(Scratch)...$"
    .endif

SSAnne_CaptainsOffice_Text_ThankYouHaveHMForCut::
    .ifdef ENGLISH
    .string "CAPTAIN: Whew! Thank you!\n"
    .string "I'm feeling much better now.\p"
    .string "You want to see my hidden CUT\n"
    .string "technique?\p"
    .string "I could show you my prized CUT\n"
    .string "technique if I weren't so ill…\p"
    .string "I know! You can have this!\n"
    .string "This HIDDEN MACHINE!\p"
    .string "Teach CUT to your POKéMON, and\n"
    .string "you can see it CUT anytime!$"
    .endif
    .ifdef SPANISH
    .string "CAPITÁN: ¡Uff! ¡Gracias!\n"
    .string "Ya me siento mucho mejor...\p"
    .string "¿Quieres ver mi técnica de CORTAR?\p"
    .string "Te la mostraría si no estuviera\n"
    .string "tan mareado.\p"
    .string "¡Ya sé!\n"
    .string "¡Toma esto!\p"
    .string "¡Enséñasela a tu POKéMON\n"
    .string "y en breve estará CORTANDO!$"
    .endif

SSAnne_CaptainsOffice_Text_ObtainedHM01FromCaptain::
    .ifdef ENGLISH
    .string "{PLAYER} obtained HM01\n"
    .string "from the CAPTAIN!$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo la MO01\n"
    .string "de manos del CAPITÁN!$"
    .endif

SSAnne_CaptainsOffice_Text_ExplainCut::
    .ifdef ENGLISH
    .string "Using CUT, you can chop down\n"
    .string "small trees.\p"
    .string "Why not try it with the trees\n"
    .string "around VERMILION CITY?$"
    .endif
    .ifdef SPANISH
    .string "Al usar CORTE, se pueden talar\n"
    .string "árboles pequeños.\p"
    .string "A lo mejor deberías probarlo con\n"
    .string "los árboles de CIUDAD CARMÍN.$"
    .endif

SSAnne_CaptainsOffice_Text_SSAnneWillSetSailSoon::
    .ifdef ENGLISH
    .string "CAPTAIN: …Whew!\p"
    .string "Now that I'm not sick anymore,\n"
    .string "I guess it's time.\p"
    .string "The S.S. ANNE will set sail soon!\p"
    .string "Farewell, until our return to\n"
    .string "VERMILION CITY!$"
    .endif
    .ifdef SPANISH
    .string "CAPITÁN: ¡Bien!\p"
    .string "¡Ahora que ya no estoy mareado,\n"
    .string "creo que deberíamos irnos!\p"
    .string "¡El S.S. ANNE zarpará pronto!\p"
    .string "¡Adiós, hasta que volvamos\n"
    .string "a CIUDAD CARMÍN!$"
    .endif

SSAnne_CaptainsOffice_Text_YouHaveNoRoomForThis::
    .ifdef ENGLISH
    .string "Oh, no!\n"
    .string "You have no room for this!$"
    .endif
    .ifdef SPANISH
    .string "¡Oh, no!\n"
    .string "¡No tienes sitio para esto!$"
    .endif

SSAnne_CaptainsOffice_Text_YuckShouldntHaveLooked::
    .ifdef ENGLISH
    .string "Yuck!\n"
    .string "Shouldn't have looked!$"
    .endif
    .ifdef SPANISH
    .string "¡Puaj!\n"
    .string "¡No debería haber mirado!$"
    .endif

SSAnne_CaptainsOffice_Text_HowToConquerSeasickness::
    .ifdef ENGLISH
    .string "How to Conquer Seasickness…\n"
    .string "The CAPTAIN's reading this!$"
    .endif
    .ifdef SPANISH
    .string "Cómo combatir el mareo...\n"
    .string "¡El CAPITÁN está leyendo esto!$"
    .endif

