SSAnne_2F_Room4_Text_LamarIntro::
    .ifdef ENGLISH
    .string "Which do you find more worthy,\n"
    .string "a strong or a rare POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué prefieres, un POKéMON fuerte\n"
    .string "o uno raro?$"
    .endif

SSAnne_2F_Room4_Text_LamarDefeat::
    .ifdef ENGLISH
    .string "I must salute you!$"
    .endif
    .ifdef SPANISH
    .string "¡Debo felicitarte!$"
    .endif

SSAnne_2F_Room4_Text_LamarPostBattle::
    .ifdef ENGLISH
    .string "Personally, I prefer strong and\n"
    .string "rare POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡Prefiero los POKéMON fuertes\n"
    .string "y raros!$"
    .endif

SSAnne_2F_Room4_Text_DawnIntro::
    .ifdef ENGLISH
    .string "I don't believe I saw you at the\n"
    .string "party?$"
    .endif
    .ifdef SPANISH
    .string "No te he visto en la fiesta.$"
    .endif

SSAnne_2F_Room4_Text_DawnDefeat::
    .ifdef ENGLISH
    .string "Take it easy!$"
    .endif
    .ifdef SPANISH
    .string "¡Oye!\n"
    .string "¡¡¡No había que ponerse así!!!$"
    .endif

SSAnne_2F_Room4_Text_DawnPostBattle::
    .ifdef ENGLISH
    .string "Oh, I adore your strong POKéMON!\n"
    .string "Oh, how I envy you for them!$"
    .endif
    .ifdef SPANISH
    .string "¡Oh!\n"
    .string "¡Adoro a tus fuertes POKéMON!$"
    .endif

