SSAnne_B1F_Room4_Text_LeonardIntro::
    .ifdef ENGLISH
    .string "You know what they say about\n"
    .string "sailors and battling!$"
    .endif
    .ifdef SPANISH
    .string "¡Ya sabes lo que dicen sobre\n"
    .string "los marineros y las peleas!$"
    .endif

SSAnne_B1F_Room4_Text_LeonardDefeat::
    .ifdef ENGLISH
    .string "Right!\n"
    .string "Good battle, mate!$"
    .endif
    .ifdef SPANISH
    .string "¡Has peleado muy bien, sí, sí!$"
    .endif

SSAnne_B1F_Room4_Text_LeonardPostBattle::
    .ifdef ENGLISH
    .string "Hahaha!\n"
    .string "Want to be a sailor, mate?$"
    .endif
    .ifdef SPANISH
    .string "¡Ajá!\n"
    .string "¿Quieres unirte a los marineros?$"
    .endif

SSAnne_B1F_Room4_Text_DuncanIntro::
    .ifdef ENGLISH
    .string "Come on, then!\n"
    .string "My sailor's pride is at stake!$"
    .endif
    .ifdef SPANISH
    .string "¡Está en juego mi fama de\n"
    .string "marinero!$"
    .endif

SSAnne_B1F_Room4_Text_DuncanDefeat::
    .ifdef ENGLISH
    .string "Your spirit sank me!$"
    .endif
    .ifdef SPANISH
    .string "¡Menuda paliza!$"
    .endif

SSAnne_B1F_Room4_Text_DuncanPostBattle::
    .ifdef ENGLISH
    .string "Did you see the FISHING GURU in\n"
    .string "VERMILION CITY?$"
    .endif
    .ifdef SPANISH
    .string "¿Viste al GURÚ de los PESCADORES\n"
    .string "en CIUDAD CARMÍN?$"
    .endif

