SSAnne_B1F_Room3_Text_DylanIntro::
    .ifdef ENGLISH
    .string "I like feisty kids like you!$"
    .endif
    .ifdef SPANISH
    .string "¡Me gusta la gente activa como tú!$"
    .endif

SSAnne_B1F_Room3_Text_DylanDefeat::
    .ifdef ENGLISH
    .string "Argh!\n"
    .string "Lost it!$"
    .endif
    .ifdef SPANISH
    .string "¡Argh!\n¡He perdido!$"
    .endif

SSAnne_B1F_Room3_Text_DylanPostBattle::
    .ifdef ENGLISH
    .string "Sea POKéMON live in deep water.\n"
    .string "You'll need a ROD to fish them up!$"
    .endif
    .ifdef SPANISH
    .string "Los POKéMON del mar viven en las\nprofundidades.\l¡Necesitarás una CAÑA!$"
    .endif

