SSAnne_Deck_Text_ShipDepartingSoon::
    .ifdef ENGLISH
    .string "The party's over.\n"
    .string "The ship will be departing soon.$"
    .endif
    .ifdef SPANISH
    .string "¡Se acabó la fiesta!\n"
    .string "¡El barco zarpará pronto!$"
    .endif

SSAnne_Deck_Text_ScrubbingDecksHardWork::
    .ifdef ENGLISH
    .string "Whew!\n"
    .string "Scrubbing decks is hard work!$"
    .endif
    .ifdef SPANISH
    .string "¡Limpiar las cubiertas es\n"
    .string "un trabajo duro!$"
    .endif

SSAnne_Deck_Text_FeelSeasick::
    .ifdef ENGLISH
    .string "Urf… I feel ill…\p"
    .string "I got seasick, so I stepped out to\n"
    .string "get some air…$"
    .endif
    .ifdef SPANISH
    .string "¡Uff! Me siento fatal...\p"
    .string "He salido a tomar el aire.$"
    .endif

SSAnne_Deck_Text_EdmondIntro::
    .ifdef ENGLISH
    .string "Hey, matey!\p"
    .string "Let's do a little jig!$"
    .endif
    .ifdef SPANISH
    .string "¡Eh, colega!\p"
    .string "¡Bailemos una jota!$"
    .endif

SSAnne_Deck_Text_EdmondDefeat::
    .ifdef ENGLISH
    .string "You're impressive!$"
    .endif
    .ifdef SPANISH
    .string "¡Eres impresionante!$"
    .endif

SSAnne_Deck_Text_EdmondPostBattle::
    .ifdef ENGLISH
    .string "How many kinds of POKéMON do you\n"
    .string "think there are in this big world?$"
    .endif
    .ifdef SPANISH
    .string "¿Cuántos tipos de POKéMON crees\n"
    .string "que hay?$"
    .endif

SSAnne_Deck_Text_TrevorIntro::
    .ifdef ENGLISH
    .string "Ahoy, there!\n"
    .string "Are you seasick?$"
    .endif
    .ifdef SPANISH
    .string "¡Eh, hola!\n"
    .string "¿Tienes mareo?$"
    .endif

SSAnne_Deck_Text_TrevorDefeat::
    .ifdef ENGLISH
    .string "I was just careless!$"
    .endif
    .ifdef SPANISH
    .string "¡No he estado muy atento!$"
    .endif

SSAnne_Deck_Text_TrevorPostBattle::
    .ifdef ENGLISH
    .string "My pa said there are 100 kinds of\n"
    .string "POKéMON. I think there are more.$"
    .endif
    .ifdef SPANISH
    .string "Mi papá decía que hay 100 tipos\n"
    .string "de POKéMON. Pero yo creo que\l"
    .string "hay más.$"
    .endif

