SSAnne_2F_Room2_Text_BrooksIntro::
    .ifdef ENGLISH
    .string "Competing against the young keeps\n"
    .string "me youthful.$"
    .endif
    .ifdef SPANISH
    .string "¡Competir contra los jóvenes\n"
    .string "me mantiene como un chaval!$"
    .endif

SSAnne_2F_Room2_Text_BrooksDefeat::
    .ifdef ENGLISH
    .string "Good match!\n"
    .string "Ah, I feel young again!$"
    .endif
    .ifdef SPANISH
    .string "¡Buena pelea!\n"
    .string "¡Vuelvo a sentirme joven!$"
    .endif

SSAnne_2F_Room2_Text_BrooksPostBattle::
    .ifdef ENGLISH
    .string "Fifteen years ago, I would\n"
    .string "have won!$"
    .endif
    .ifdef SPANISH
    .string "¡Hace 15 años, yo habría ganado!$"
    .endif

SSAnne_2F_Room2_Text_DaleIntro::
    .ifdef ENGLISH
    .string "Check out what I fished up!$"
    .endif
    .ifdef SPANISH
    .string "¡Mira lo que he pescado!$"
    .endif

SSAnne_2F_Room2_Text_DaleDefeat::
    .ifdef ENGLISH
    .string "I'm all out!$"
    .endif
    .ifdef SPANISH
    .string "¡Estoy acabado!$"
    .endif

SSAnne_2F_Room2_Text_DalePostBattle::
    .ifdef ENGLISH
    .string "Party?\p"
    .string "The cruise ship's party should be\n"
    .string "over by now.$"
    .endif
    .ifdef SPANISH
    .string "¿Una fiesta?\p"
    .string "La fiesta del crucero debe de\n"
    .string "haber terminado.$"
    .endif

