SSAnne_1F_Room2_Text_TylerIntro::
    .ifdef ENGLISH
    .string "I love POKéMON!\n"
    .string "Do you?$"
    .endif
    .ifdef SPANISH
    .string "¡Me gustan los POKéMON!\n"
    .string "¿Y a ti?$"
    .endif

SSAnne_1F_Room2_Text_TylerDefeat::
    .ifdef ENGLISH
    .string "Wow! \n"
    .string "You're great!$"
    .endif
    .ifdef SPANISH
    .string "¡Guauu!\n"
    .string "¡Eres genial!$"
    .endif

SSAnne_1F_Room2_Text_TylerPostBattle::
    .ifdef ENGLISH
    .string "Listen, listen!\n"
    .string "Let me be your friend, okay?\p"
    .string "Then we can trade POKéMON and\n"
    .string "do stuff.$"
    .endif
    .ifdef SPANISH
    .string "Seamos amigos, ¿vale?\p"
    .string "¡Y así podremos intercambiar\n"
    .string "POKéMON!$"
    .endif

SSAnne_1F_Room2_Text_AnnIntro::
    .ifdef ENGLISH
    .string "I collected these POKéMON\n"
    .string "from all around the world!$"
    .endif
    .ifdef SPANISH
    .string "¡He atrapado POKéMON por todo\n"
    .string "el mundo!$"
    .endif

SSAnne_1F_Room2_Text_AnnDefeat::
    .ifdef ENGLISH
    .string "Oh, no!\n"
    .string "I went around the world for these!$"
    .endif
    .ifdef SPANISH
    .string "¡Vaya!\n"
    .string "¡Con lo que he viajado por ellos!$"
    .endif

SSAnne_1F_Room2_Text_AnnPostBattle::
    .ifdef ENGLISH
    .string "You hurt my poor POKéMON!\p"
    .string "I demand that you heal them at a\n"
    .string "POKéMON CENTER!$"
    .endif
    .ifdef SPANISH
    .string "¡Les has hecho daño a mis pobres\n"
    .string "POKéMON!\p"
    .string "¡¡¡Y exijo que los cures en un\n"
    .string "CENTRO POKéMON!!!$"
    .endif

SSAnne_1F_Room2_Text_CruisingAroundWorld::
    .ifdef ENGLISH
    .string "We are cruising around the world,\n"
    .string "my children and I.$"
    .endif
    .ifdef SPANISH
    .string "¡Viajamos en crucero por todo\n"
    .string "el mundo!$"
    .endif

