SSAnne_2F_Room1_Text_SleepingMonLookedLikeThis::
    .ifdef ENGLISH
    .string "I've journeyed far and wide, but in\n"
    .string "all my travels I've never seen\l"
    .string "any POKéMON sleep like this one!\p"
    .string "It was something like this!$"
    .endif
    .ifdef SPANISH
    .string "¡Durante todos mis viajes jamás\n"
    .string "había visto a un POKéMON que\l"
    .string "durmiera tanto!\p"
    .string "¡Era algo así!...$"
    .endif

