ViridianForest_Text_FriendsItchingToBattle::
    .ifdef ENGLISH
    .string "I came here with some friends to\n"
    .string "catch us some BUG POKéMON!\p"
    .string "They're all itching to get into\n"
    .string "some POKéMON battles!$"
    .endif
    .ifdef SPANISH
    .string "¡Vine aquí con unos amigos!\p"
    .string "¡Van en busca de combates\n"
    .string "POKéMON!$"
    .endif

ViridianForest_Text_RickIntro::
    .ifdef ENGLISH
    .string "Hey! You have POKéMON!\n"
    .string "Come on!\l"
    .string "Let's battle 'em!$"
    .endif
    .ifdef SPANISH
    .string "¡Eh! ¡Tienes POKéMON!\n"
    .string "¡Sí!\l"
    .string "¡Al ataque!$"
    .endif

ViridianForest_Text_RickDefeat::
    .ifdef ENGLISH
    .string "No!\nCATERPIE can't hack it!$"
    .endif
    .ifdef SPANISH
    .string "¡No!\n¡Mi CATERPIE no pudo más!$"
    .endif

ViridianForest_Text_RickPostBattle::
    .ifdef ENGLISH
    .string "Ssh! You'll scare the bugs away.\n"
    .string "Another time, okay?$"
    .endif
    .ifdef SPANISH
    .string "¡Ssh!\n"
    .string "¡Vas a espantar a los bichos!...$"
    .endif


ViridianForest_Text_DougIntro::
    .ifdef ENGLISH
    .string "Yo!\n"
    .string "You can't jam out if you're a\l"
    .string "POKéMON TRAINER!$"
    .endif
    .ifdef SPANISH
    .string "¡Eh!\n"
    .string "¡Hay que tener disciplina para ser\l"
    .string "ENTRENADOR POKéMON!$"
    .endif

ViridianForest_Text_DougDefeat::
    .ifdef ENGLISH
    .string "Huh?\n"
    .string "I ran out of POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "¿Será posible?\n"
    .string "¡No me quedan más POKéMON!$"
    .endif

ViridianForest_Text_DougPostBattle::
    .ifdef ENGLISH
    .string "That totally stinks! I'm going to\n"
    .string "catch some stronger ones!$"
    .endif
    .ifdef SPANISH
    .string "¡Vaya!\n"
    .string "¡Voy a atrapar unos más fuertes!$"
    .endif

ViridianForest_Text_SammyIntro::
    .ifdef ENGLISH
    .string "Hey, wait up!\n"
    .string "What's the hurry? Why the rush?$"
    .endif
    .ifdef SPANISH
    .string "¡Eh, espera!\n"
    .string "¿Por qué tienes tanta prisa?$"
    .endif

ViridianForest_Text_SammyDefeat::
    .ifdef ENGLISH
    .string "I give!\n"
    .string "You're good at this!$"
    .endif
    .ifdef SPANISH
    .string "¡Me rindo!\n"
    .string "¡Eres demasiado fuerte!$"
    .endif

ViridianForest_Text_SammyPostBattle::
    .ifdef ENGLISH
    .string "Sometimes, you can find stuff on\n"
    .string "the ground.\p"
    .string "I'm looking for the stuff I\n"
    .string "dropped. Can you help me?$"
    .endif
    .ifdef SPANISH
    .string "¡A veces puedes encontrar cosas\n"
    .string "en el suelo!\p"
    .string "¡Estoy buscando los objetos\n"
    .string "que se me cayeron!$"
    .endif

ViridianForest_Text_AnthonyIntro::
    .ifdef ENGLISH
    .string "I might be little, but I won't like\n"
    .string "it if you go easy on me!$"
    .endif
    .ifdef SPANISH
    .string "No soy especialmente grande, ¡pero\n"
    .string "tampoco soy ningún enclenque!$"
    .endif

ViridianForest_Text_AnthonyDefeat::
    .ifdef ENGLISH
    .string "Oh, boo.\n"
    .string "Nothing went right.$"
    .endif
    .ifdef SPANISH
    .string "Vaya, pues se ve que tampoco\n"
    .string "soy demasiado fuerte...$"
    .endif

ViridianForest_Text_AnthonyPostBattle::
    .ifdef ENGLISH
    .string "I lost some of my allowance…$"
    .endif
    .ifdef SPANISH
    .string "Así no hay forma de ahorrar...$"
    .endif

ViridianForest_Text_CharlieIntro::
    .ifdef ENGLISH
    .string "Did you know that POKéMON evolve?$"
    .endif
    .ifdef SPANISH
    .string "¿Sabes que los POKéMON\n"
    .string "evolucionan?$"
    .endif

ViridianForest_Text_CharlieDefeat::
    .ifdef ENGLISH
    .string "Oh!\n"
    .string "I lost!$"
    .endif
    .ifdef SPANISH
    .string "¡Oh! ¡He perdido!$"
    .endif

ViridianForest_Text_CharliePostBattle::
    .ifdef ENGLISH
    .string "BUG POKéMON evolve quickly.\n"
    .string "They're a lot of fun!$"
    .endif
    .ifdef SPANISH
    .string "Los POKéMON evolucionan\n"
    .string "muy rápido. ¡Son geniales!$"
    .endif

ViridianForest_Text_RanOutOfPokeBalls::
    .ifdef ENGLISH
    .string "I was throwing POKé BALLS to\n"
    .string "catch POKéMON, and I ran out.\p"
    .string "That's why you can never have too\n"
    .string "many POKé BALLS.$"
    .endif
    .ifdef SPANISH
    .string "¡Me quedé sin POKé BALLS con\n"
    .string "las que atrapar a los POKéMON!\p"
    .string "¡Deberías llevar algunas extra!$"
    .endif

ViridianForest_Text_AvoidGrassyAreasWhenWeak::
    .ifdef ENGLISH
    .string "TRAINER TIPS\p"
    .string "If your POKéMON are weak and you\n"
    .string "want to avoid battles, stay away\l"
    .string "from grassy areas!$"
    .endif
    .ifdef SPANISH
    .string "PISTAS ENTRENADOR\p"
    .string "Si quieres evitar los combates,\n"
    .string "¡aléjate de las zonas de hierba!$"
    .endif

ViridianForest_Text_UseAntidoteForPoison::
    .ifdef ENGLISH
    .string "For poison, use ANTIDOTE!\n"
    .string "Get it at POKéMON MARTS!$"
    .endif
    .ifdef SPANISH
    .string "¡Usa ANTÍDOTO contra el veneno!\n"
    .string "¡Lo conseguirás en las TIENDAS\l"
    .string "POKéMON!$"
    .endif

ViridianForest_Text_ContactOakViaPCToRatePokedex::
    .ifdef ENGLISH
    .string "TRAINER TIPS\p"
    .string "Contact PROF. OAK via a PC to\n"
    .string "get your POKéDEX evaluated!$"
    .endif
    .ifdef SPANISH
    .string "PISTAS ENTRENADOR\p"
    .string "¡Para evaluar tu POKéDEX, llama\n"
    .string "al PROF. OAK vía PC!$"
    .endif

ViridianForest_Text_CantCatchOwnedMons::
    .ifdef ENGLISH
    .string "TRAINER TIPS\p"
    .string "You can't catch a POKéMON that\n"
    .string "belongs to someone else.\p"
    .string "Throw POKé BALLS only at wild\n"
    .string "POKéMON to catch them!$"
    .endif
    .ifdef SPANISH
    .string "PISTAS ENTRENADOR\p"
    .string "¡No robes los POKéMON de otros\n"
    .string "ENTRENADORES!\p"
    .string "¡Captura sólo POKéMON salvajes\n"
    .string "con las POKé BALLS!$"
    .endif

ViridianForest_Text_WeakenMonsBeforeCapture::
    .ifdef ENGLISH
    .string "TRAINER TIPS\p"
    .string "Weaken POKéMON before attempting\n"
    .string "capture!\p"
    .string "When healthy, they may escape!$"
    .endif
    .ifdef SPANISH
    .string "PISTAS ENTRENADOR\p¡Debilita a los POKéMON antes\n"
    .string "de intentar capturarlos!\p"
    .string "¡Si están fuertes, podrían escapar!$"
    .endif

ViridianForest_Text_LeavingViridianForest::
    .ifdef ENGLISH
    .string "LEAVING VIRIDIAN FOREST\n"
    .string "PEWTER CITY AHEAD$"
    .endif
    .ifdef SPANISH
    .string "SALIENDO DEL BOSQUE VERDE,\n"
    .string "SE ENCUENTRA CIUDAD PLATEADA$"
    .endif

