MtMoon_B2F_Text_MiguelIntro::
    .ifdef ENGLISH
    .string "Hey, stop!\p"
    .string "I found these fossils!\n"
    .string "They're both mine!$"
    .endif
    .ifdef SPANISH
    .string "¡No toques nada!\p"
    .string "¡Yo encontré estos fósiles!\n"
    .string "¡Son míos!$"
    .endif

MtMoon_B2F_Text_MiguelDefeat::
    .ifdef ENGLISH
    .string "Okay!\n"
    .string "I'll share!$"
    .endif
    .ifdef SPANISH
    .string "¡De acuerdo!\n"
    .string "¡Los compartiré!$"
    .endif

MtMoon_B2F_Text_WellEachTakeAFossil::
    .ifdef ENGLISH
    .string "We'll each take a fossil!\n"
    .string "No being greedy!$"
    .endif
    .ifdef SPANISH
    .string "¡Uno para cada!\n"
    .string "¡No hay que ser avaricioso!$"
    .endif

MtMoon_B2F_Text_ThenThisFossilIsMine::
    .ifdef ENGLISH
    .string "All right.\n"
    .string "Then this fossil is mine!$"
    .endif
    .ifdef SPANISH
    .string "Muy bien.\n"
    .string "¡Pues éste es el mío!$"
    .endif

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils::
    .ifdef ENGLISH
    .string "Far away, on CINNABAR ISLAND,\n"
    .string "there's a POKéMON LAB.\p"
    .string "They do research on regenerating\n"
    .string "fossils.$"
    .endif
    .ifdef SPANISH
    .string "Muy lejos, en ISLA CANELA, hay\n"
    .string "un LABORATORIO de POKéMON.\p"
    .string "En él estudian cómo regenerar\n"
    .string "los fósiles de POKéMON.$"
    .endif

MtMoon_B2F_Text_Grunt1Intro::
    .ifdef ENGLISH
    .string "We, TEAM ROCKET, shall find the\n"
    .string "fossils!\p"
    .string "Reviving POKéMON from them will\n"
    .string "earn us huge riches!$"
    .endif
    .ifdef SPANISH
    .string "El TEAM ROCKET encontrará\n"
    .string "los fósiles, los revivirá ¡y los\l"
    .string "venderá!$"
    .endif

MtMoon_B2F_Text_Grunt1Defeat::
    .ifdef ENGLISH
    .string "Urgh!\n"
    .string "Now I'm mad!$"
    .endif
    .ifdef SPANISH
    .string "¡Argh!\n"
    .string "¡Eres lo peor!$"
    .endif

MtMoon_B2F_Text_Grunt1PostBattle::
    .ifdef ENGLISH
    .string "You made me mad!\n"
    .string "TEAM ROCKET will blacklist you!$"
    .endif
    .ifdef SPANISH
    .string "¡Eres un fastidio! ¡El TEAM ROCKET\n"
    .string "te pondrá en la lista negra!$"
    .endif

MtMoon_B2F_Text_Grunt2Intro::
    .ifdef ENGLISH
    .string "We, TEAM ROCKET, are POKéMON\n"
    .string "gangsters!\l"
    .string "We strike fear with our strength!$"
    .endif
    .ifdef SPANISH
    .string "¡Nosotros, el TEAM ROCKET,\n"
    .string "somos los bandidos POKéMON!$"
    .endif

MtMoon_B2F_Text_Grunt2Defeat::
    .ifdef ENGLISH
    .string "I blew it!$"
    .endif
    .ifdef SPANISH
    .string "¡Lo he hecho fatal!$"
    .endif

MtMoon_B2F_Text_Grunt2PostBattle::
    .ifdef ENGLISH
    .string "Darn it all!\n"
    .string "My associates won't stand for this!$"
    .endif
    .ifdef SPANISH
    .string "¿Será posible?\n"
    .string "¡Mis compañeros me vengarán!$"
    .endif

MtMoon_B2F_Text_Grunt3Intro::
    .ifdef ENGLISH
    .string "We're pulling a big job here!\n"
    .string "Get lost, kid!$"
    .endif
    .ifdef SPANISH
    .string "¡Nuestro trabajo aquí es muy\n"
    .string "importante! ¡Lárgate, enclenque!$"
    .endif

MtMoon_B2F_Text_Grunt3Defeat::
    .ifdef ENGLISH
    .string "So, you are good…$"
    .endif
    .ifdef SPANISH
    .string "Pues eres muy fuerte...$"
    .endif

MtMoon_B2F_Text_Grunt3PostBattle::
    .ifdef ENGLISH
    .string "If you find a fossil, give it to me\n"
    .string "and scram!$"
    .endif
    .ifdef SPANISH
    .string "Si encuentras un fósil, ¡dámelo\n"
    .string "y lárgate!$"
    .endif

MtMoon_B2F_Text_Grunt4Intro::
    .ifdef ENGLISH
    .string "Little kids shouldn't be messing\n"
    .string "around with grown-ups!\p"
    .string "It could be bad news!$"
    .endif
    .ifdef SPANISH
    .string "¡Los niños no deberían molestar\n"
    .string "a los adultos!$"
    .endif

MtMoon_B2F_Text_Grunt4Defeat::
    .ifdef ENGLISH
    .string "I'm steamed!$"
    .endif
    .ifdef SPANISH
    .string "¡Estoy muy enfadado!$"
    .endif

MtMoon_B2F_Text_Grunt4PostBattle::
    .ifdef ENGLISH
    .string "POKéMON lived here long before\n"
    .string "people came.$"
    .endif
    .ifdef SPANISH
    .string "Los POKéMON vivían aquí mucho\n"
    .string "antes de que llegara la gente.$"
    .endif

MtMoon_B2F_Text_YouWantDomeFossil::
    .ifdef ENGLISH
    .string "Do you want the DOME FOSSIL?$"
    .endif
    .ifdef SPANISH
    .string "¿Quieres el FÓSIL DOMO?$"
    .endif

MtMoon_B2F_Text_YouWantHelixFossil::
    .ifdef ENGLISH
    .string "Do you want the HELIX FOSSIL?$"
    .endif
    .ifdef SPANISH
    .string "¿Quieres el FÓSIL HELIX?$"
    .endif

MtMoon_B2F_Text_ObtainedHelixFossil::
    .ifdef ENGLISH
    .string "Obtained the HELIX FOSSIL!$"
    .endif
    .ifdef SPANISH
    .string "¡Obtuviste el FÓSIL HELIX!$"
    .endif

MtMoon_B2F_Text_ObtainedDomeFossil::
    .ifdef ENGLISH
    .string "Obtained the DOME FOSSIL!$"
    .endif
    .ifdef SPANISH
    .string "¡Obtuviste el FÓSIL DOMO!$"
    .endif

