SSAnne_B1F_Room1_Text_PhillipIntro::
    .ifdef ENGLISH
    .string "Matey, you're walking the plank if\n"
    .string "you lose!$"
    .endif
    .ifdef SPANISH
    .string "¡Como pierdas, caminarás\n"
    .string "por el tablón!$"
    .endif

SSAnne_B1F_Room1_Text_PhillipDefeat::
    .ifdef ENGLISH
    .string "Argh!\n"
    .string "Beaten by a kid!$"
    .endif
    .ifdef SPANISH
    .string "¡Argh! ¡Derrotado por alguien\n"
    .string "más joven que yo!$"
    .endif

SSAnne_B1F_Room1_Text_PhillipPostBattle::
    .ifdef ENGLISH
    .string "When we're out at sea, jellyfish\n"
    .string "POKéMON sometimes drift by.$"
    .endif
    .ifdef SPANISH
    .string "A veces, algunas medusas caen\n"
    .string "dentro del barco.$"
    .endif

SSAnne_B1F_Room1_Text_BarnyIntro::
    .ifdef ENGLISH
    .string "Hello, stranger!\p"
    .string "I can't tell if you're from the seas\n"
    .string "or mountains, but stop and chat.\p"
    .string "All my POKéMON are from the sea.$"
    .endif
    .ifdef SPANISH
    .string "¡Eh, tú!\p"
    .string "¡No sé si eres de tierra o mar, \n"
    .string "pero para y habla conmigo!\p"
    .string "¡Todos mis POKéMON vienen del mar!$"
    .endif

SSAnne_B1F_Room1_Text_BarnyDefeat::
    .ifdef ENGLISH
    .string "Darn!\n"
    .string "I let that one get away!$"
    .endif
    .ifdef SPANISH
    .string "¡Vaya!\n"
    .string "¡He dejado que te escaparas!$"
    .endif

SSAnne_B1F_Room1_Text_BarnyPostBattle::
    .ifdef ENGLISH
    .string "I was going to make you my\n"
    .string "assistant, too!$"
    .endif
    .ifdef SPANISH
    .string "¡Yo también te iba a hacer\n"
    .string "mi ayudante!$"
    .endif

