SSAnne_1F_Corridor_Text_LeStrongSilentType::
    .ifdef ENGLISH
    .string "Bonjour!\n"
    .string "I am le waiter on this ship!\p"
    .string "I will be happy to serve you\n"
    .string "anything you please!\p"
    .string "… … …\n"
    .string "Ah! Le strong silent type!$"
    .endif
    .ifdef SPANISH
    .string "¡Bonjour!\n"
    .string "¡Soy el camarero de este barco!\p"
    .string "¡Encantado de servirte en todo\n"
    .string "lo que quieras!\p"
    .string "Tienes cara de ser una persona\n"
    .string "fuerte y discreta.$"
    .endif

SSAnne_1F_Corridor_Text_PassengersAreRestless::
    .ifdef ENGLISH
    .string "The passengers are restless from\n"
    .string "this long voyage.\p"
    .string "You might be challenged by the\n"
    .string "more bored ones!$"
    .endif
    .ifdef SPANISH
    .string "¡Los pasajeros se están\n"
    .string "impacientando!\p"
    .string "¡Los que están más aburridos\n"
    .string "podrían retarte!$"
    .endif

