DiglettsCave_NorthEntrance_RockTunnelPitchBlack::
    .ifdef ENGLISH
    .string "I went inside ROCK TUNNEL, but it's\n"
    .string "pitch-black and scary in there.\p"
    .string "If I could get a POKéMON to use\n"
    .string "FLASH and light it up…$"
    .endif
    .ifdef SPANISH
    .string "Fui al TÚNEL ROCA, pero\n"
    .string "está oscuro y me da miedo.\p"
    .string "¡Si el DESTELLO de un POKéMON\n"
    .string "pudiera alumbrarlo...!$"
    .endif

