SSAnne_2F_Room3_Text_SeenMonsFerryPeople::
    .ifdef ENGLISH
    .string "Ah, yes, I have seen some POKéMON\n"
    .string "ferry people across the water!$"
    .endif
    .ifdef SPANISH
    .string "¡Ah, sí! ¡Vi a unos POKéMON\n"
    .string "transportando a gente por el agua!$"
    .endif

SSAnne_2F_Room3_Text_SomeTreesCanBeCutDown::
    .ifdef ENGLISH
    .string "Small trees can be chopped down\n"
    .string "using the move CUT.\p"
    .string "But remember this!\n"
    .string "CUT is an HM technique.\p"
    .string "Once learned, it is not so easily\n"
    .string "discarded.$"
    .endif
    .ifdef SPANISH
    .string "Los POKéMON pueden CORTAR\n"
    .string "pequeños arbustos.\p"
    .string "Pero ten en cuenta que CORTE\n"
    .string "es una técnica de MO.\p"
    .string "Una vez aprendida, cuesta mucho\n"
    .string "olvidarla.$"
    .endif

