SSAnne_2F_Corridor_Text_ThisShipIsLuxuryLiner::
    .ifdef ENGLISH
    .string "This ship, she is a luxury liner for\n"
    .string "TRAINERS of the world!\p"
    .string "At every port, we hold parties with\n"
    .string "invited TRAINERS.$"
    .endif
    .ifdef SPANISH
    .string "¡Este lujoso barco es para\n"
    .string "los ENTRENADORES!\p"
    .string "¡En cada puerto celebramos\n"
    .string "una fiesta para los ENTRENADORES!$"
    .endif

SSAnne_2F_Corridor_Text_RivalIntro::
    .ifdef ENGLISH
    .string "{RIVAL}: Bonjour!\n"
    .string "{PLAYER}!\p"
    .string "Imagine seeing you here!\n"
    .string "{PLAYER}, were you really invited?\p"
    .string "So how's your POKéDEX coming?\p"
    .string "I already caught 40 kinds, pal.\n"
    .string "Different kinds are everywhere.\p"
    .string "Crawl around in grassy areas, and\n"
    .string "look hard for them.$"
    .endif
    .ifdef SPANISH
    .string "{RIVAL}:\n"
    .string "¡Bonjour, {PLAYER}!\p"
    .string "¡Ya sabía yo que te vería por\n"
    .string "aquí! ¿{PLAYER}, te han invitado?\p"
    .string "¿Y qué tal va tu POKéDEX?\p"
    .string "¡Yo ya tengo 40 POKéMON!\n"
    .string "¡Están por todas partes!\p"
    .string "¡Adéntrate en las zonas de hierba\n"
    .string "alta!$"
    .endif

SSAnne_2F_Corridor_Text_RivalDefeat::
    .ifdef ENGLISH
    .string "Humph!\p"
    .string "At least you're raising your\n"
    .string "POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "¡Vaya!\p"
    .string "¡Parece que has entrenado bien\n"
    .string "a tus POKéMON!$"
    .endif

SSAnne_2F_Corridor_Text_RivalVictory::
    .string "{PLAYER}‥！\n"
    .string "ふなよい　してるのか！\p"
    .string "もっと　からだ\n"
    .string "きたえた　ほうが　いいぜ！$"

SSAnne_2F_Corridor_Text_RivalPostBattle::
    .ifdef ENGLISH
    .string "{RIVAL}: I heard there was a CUT\n"
    .string "master on board.\p"
    .string "But he was just a seasick old man!\p"
    .string "CUT itself is really useful.\n"
    .string "Yup, it'll be handy.\p"
    .string "You should go see him, too.\n"
    .string "Smell ya!$"
    .endif
    .ifdef SPANISH
    .string "{RIVAL}: Decían que había un\n"
    .string "maestro del CORTE a bordo.\p"
    .string "¡Pero sólo era un viejo mareado!\p"
    .string "¡Sin embargo, la técnica del CORTE\n"
    .string "es muy útil!\p"
    .string "¡Deberías ir a verle!\n"
    .string "¡Hasta luego!$"
    .endif

