SSAnne_1F_Room7_Text_ThomasIntro::
    .ifdef ENGLISH
    .string "I am but a solitary traveler…\p"
    .string "My sole companions and friends are\n"
    .string "POKéMON I caught on my journeys…$"
    .endif
    .ifdef SPANISH
    .string "¡Viajo solo!\p"
    .string "¡Mis POKéMON son mis únicos amigos!$"
    .endif

SSAnne_1F_Room7_Text_ThomasDefeat::
    .ifdef ENGLISH
    .string "My, my friends…$"
    .endif
    .ifdef SPANISH
    .string "¡Oh! ¡Mis amigos!$"
    .endif

SSAnne_1F_Room7_Text_ThomasPostBattle::
    .ifdef ENGLISH
    .string "You should be nice to friends!$"
    .endif
    .ifdef SPANISH
    .string "¡Deberías portarte bien con\n"
    .string "los amigos!$"
    .endif

