SSAnne_2F_Room6_Text_CaptainIsAwfullySick::
    .ifdef ENGLISH
    .string "The CAPTAIN said he's awfully sick.\n"
    .string "He was all pale.$"
    .endif
    .ifdef SPANISH
    .string "¡El CAPITÁN parecía muy mareado\n"
    .string "y pálido!$"
    .endif

SSAnne_2F_Room6_Text_ManyPeopleGetSeasick::
    .ifdef ENGLISH
    .string "I hear many people get seasick.$"
    .endif
    .ifdef SPANISH
    .string "¡Dicen que hay mucha gente que\n"
    .string "se marea!$"
    .endif

