SSAnne_1F_Room3_Text_CruiseIsElegantAndCozy::
    .ifdef ENGLISH
    .string "A world cruise is so elegant yet\n"
    .string "cozy!$"
    .endif
    .ifdef SPANISH
    .string "¡Los cruceros son tan elegantes\n"
    .string "y acogedores!$"
    .endif

SSAnne_1F_Room3_Text_AlwaysTravelWithWigglytuff::
    .ifdef ENGLISH
    .string "I always travel with WIGGLYTUFF.\n"
    .string "I never leave home without it.$"
    .endif
    .ifdef SPANISH
    .string "¡Siempre viajo con WIGGLYTUFF!$"
    .endif

SSAnne_1F_Room3_Text_Wigglytuff::
    .ifdef ENGLISH
    .string "WIGGLYTUFF: Puup pupuu!$"
    .endif
    .ifdef SPANISH
    .string "WIGGLYTUFF: ¡Wig, tuuuf, tuuuf!$"
    .endif

