SSAnne_B1F_Room2_Text_HueyIntro::
    .ifdef ENGLISH
    .string "Even us sailors have POKéMON, too!$"
    .endif
    .ifdef SPANISH
    .string "¡Los marineros también tenemos\nPOKéMON!$"
    .endif

SSAnne_B1F_Room2_Text_HueyDefeat::
    .ifdef ENGLISH
    .string "Okay, you're not bad.$"
    .endif
    .ifdef SPANISH
    .string "¡Eres bastante fuerte!$"
    .endif

SSAnne_B1F_Room2_Text_HueyPostBattle::
    .ifdef ENGLISH
    .string "We caught all our POKéMON while\n"
    .string "we were out at sea.$"
    .endif
    .ifdef SPANISH
    .string "¡Pescamos a todos nuestros POKéMON\n"
    .string "en alta mar!$"
    .endif

