DiglettsCave_SouthEntrance_Text_DiglettDugThisTunnel::
    .ifdef ENGLISH
    .string "Well, isn't this a surprise!\n"
    .string "DIGLETT dug this long tunnel!\p"
    .string "It goes right to VIRIDIAN CITY,\n"
    .string "they tell me.$"
    .endif
    .ifdef SPANISH
    .string "¡Vaya sorpresa! ¡Los DIGLETT\n"
    .string "cavaron este largo túnel!\p"
    .string "¡Va a CIUDAD VERDE!$"
    .endif

